version: '3'
services:
  app:
    container_name: container-petsup
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    command: ["npm", "run", "dev", "--", "--host"]